### ISSUE TITLE
prebuilt Docker image doesn't work

### ISSUE THREAD

**Issue by ntman4real** [brennerm/docker-registry-frontend#1]
Tried using via Portainer, and then just locally.

Can Get the initial splash screen, but as soon as I add my reg, I get a "Failed to load resource: the server responded with a status of 500 (INTERNAL SERVER ERROR)" message and can't do anything from that point forward.  

Here is the error log:
`2017-06-29T19:27:21.847857904Z [2017-06-29 19:27:21,843] ERROR in app: Exception on / [GET]
2017-06-29T19:27:21.847913460Z Traceback (most recent call last):
2017-06-29T19:27:21.847934667Z   File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1982, in wsgi_app
2017-06-29T19:27:21.847954915Z     response = self.full_dispatch_request()
2017-06-29T19:27:21.847979054Z   File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1614, in full_dispatch_request
2017-06-29T19:27:21.847999283Z     rv = self.handle_user_exception(e)
2017-06-29T19:27:21.848018452Z   File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1517, in handle_user_exception
2017-06-29T19:27:21.848038365Z     reraise(exc_type, exc_value, tb)
2017-06-29T19:27:21.848057320Z   File "/usr/local/lib/python3.5/dist-packages/flask/_compat.py", line 33, in reraise
2017-06-29T19:27:21.848077192Z     raise value
2017-06-29T19:27:21.848096120Z   File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1612, in full_dispatch_request
2017-06-29T19:27:21.848116102Z     rv = self.dispatch_request()
2017-06-29T19:27:21.848135113Z   File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1598, in dispatch_request
2017-06-29T19:27:21.848154925Z     return self.view_functions[rule.endpoint](**req.view_args)
2017-06-29T19:27:21.848174199Z   File "main.py", line 54, in registry_overview
2017-06-29T19:27:21.848193518Z     registries=registry_web.registries)
2017-06-29T19:27:21.848212526Z   File "/usr/local/lib/python3.5/dist-packages/flask/templating.py", line 134, in render_template
2017-06-29T19:27:21.848232315Z     context, ctx.app)
2017-06-29T19:27:21.848284506Z   File "/usr/local/lib/python3.5/dist-packages/flask/templating.py", line 116, in _render
2017-06-29T19:27:21.848305480Z     rv = template.render(context)
2017-06-29T19:27:21.848324837Z   File "/usr/local/lib/python3.5/dist-packages/jinja2/environment.py", line 1008, in render
2017-06-29T19:27:21.848344702Z     return self.environment.handle_exception(exc_info, True)
2017-06-29T19:27:21.848363998Z   File "/usr/local/lib/python3.5/dist-packages/jinja2/environment.py", line 780, in handle_exception
2017-06-29T19:27:21.848383949Z     reraise(exc_type, exc_value, tb)
2017-06-29T19:27:21.848403058Z   File "/usr/local/lib/python3.5/dist-packages/jinja2/_compat.py", line 37, in reraise
2017-06-29T19:27:21.848422814Z     raise value.with_traceback(tb)
2017-06-29T19:27:21.848441844Z   File "/root/templates/registry_overview.html", line 1, in top-level template code
2017-06-29T19:27:21.848461667Z     {% extends "layout.html" %}
2017-06-29T19:27:21.848480983Z   File "/root/templates/layout.html", line 21, in top-level template code
2017-06-29T19:27:21.848500622Z     <div id="content" class="container-fluid">{% block content %}{% endblock %}</div>
2017-06-29T19:27:21.848521832Z   File "/root/templates/registry_overview.html", line 29, in block "content"
2017-06-29T19:27:21.848541828Z     <td>{{ registry.get_number_of_repos() }}</td>
2017-06-29T19:27:21.848565595Z   File "/root/docker_registry_frontend/registry.py", line 79, in get_number_of_repos
2017-06-29T19:27:21.848585734Z     return len(self.get_repos())
2017-06-29T19:27:21.848604971Z   File "/root/docker_registry_frontend/registry.py", line 315, in get_repos
2017-06-29T19:27:21.848624531Z     url=self._url)
2017-06-29T19:27:21.848643245Z   File "/root/docker_registry_frontend/registry.py", line 53, in json_request
2017-06-29T19:27:21.848662827Z     DockerRegistry.string_request(*args, **kwargs)
2017-06-29T19:27:21.848681835Z   File "/usr/lib/python3.5/json/__init__.py", line 319, in loads
2017-06-29T19:27:21.848701248Z     return _default_decoder.decode(s)
2017-06-29T19:27:21.848720218Z   File "/usr/lib/python3.5/json/decoder.py", line 339, in decode
2017-06-29T19:27:21.848739793Z     obj, end = self.raw_decode(s, idx=_w(s, 0).end())
2017-06-29T19:27:21.848758913Z   File "/usr/lib/python3.5/json/decoder.py", line 357, in raw_decode
2017-06-29T19:27:21.848778466Z     raise JSONDecodeError("Expecting value", s, err.value) from None
2017-06-29T19:27:21.848818943Z json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
2017-06-29T19:27:21.848853634Z 127.0.0.1 - - [29/Jun/2017 19:27:21] "GET / HTTP/1.0" 500 -`

**Comment by brennerm** [comment]
Hey @ntman4real,
It seems like the registry answers with an unexpected response.
Could you tell me which version of registry you are using?

**Comment by ntman4real** [comment]
the latest official. registry:latest (Created	2017-06-19 20:44:50)

**Comment by brennerm** [comment]
Unfortunately I'm not able to reproduce your issue.
Could you send me the output of the following two curl requests?

```bash
curl http://$your_registry_url:5000/v2/
```
```bash
curl http://$your_registry_url:5000/v2/_catalog
```
Depending on your setup you may need to change the port or use https. Make sure to delete any confidential content of the responses.

**Comment by brennerm** [comment]
Closing due to no response.
