### ISSUE TITLE
Timeout when try to get a list of images (based Windows Core) from a big repo

### ISSUE THREAD

**Issue by pavlovpetro** [brennerm/docker-registry-frontend#11]
Hi,
Sometimes when I try to get the list of images(tags) from the big repo(more then 5 tags) I get an "Internal Server Error". It occurs only with tags which is built on the "windowsservercore" image. I have two registries - one of them is running on the Windows, second - on Linux. But the error occurs at requests to both registries.
Docker Version: 18.03.1-ce
Version of Registries: v2.6.2
```
192.168.36.195 - - [08/Jun/2018 08:04:54] "GET /registry/docker-proxy-ua HTTP/1.1" 200 -
[2018-06-08 08:05:06,332] ERROR in app: Exception on /registry/docker-proxy-ua/repo/mssql2017/ [GET]
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.6/site-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "frontend.py", line 137, in tag_overview
    repo=urldecode_filter(repo))
  File "/usr/local/lib/python3.6/site-packages/flask/templating.py", line 135, in render_template
    context, ctx.app)
  File "/usr/local/lib/python3.6/site-packages/flask/templating.py", line 117, in _render
    rv = template.render(context)
  File "/usr/local/lib/python3.6/site-packages/jinja2/asyncsupport.py", line 76, in render
    return original_render(self, *args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/jinja2/environment.py", line 1008, in render
    return self.environment.handle_exception(exc_info, True)
  File "/usr/local/lib/python3.6/site-packages/jinja2/environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.6/site-packages/jinja2/_compat.py", line 37, in reraise
    raise value.with_traceback(tb)
  File "/root/templates/tag_overview.html", line 1, in top-level template code
    {% extends "layout.html" %}
  File "/root/templates/layout.html", line 21, in top-level template code
    <div id="content" class="container-fluid">{% block content %}{% endblock %}</div>
  File "/root/templates/tag_overview.html", line 21, in block "content"
    <td>{{ registry.get_size_of_layers(repo, tag) | to_mb }} MB</td>
  File "/root/docker_registry_frontend/registry.py", line 97, in get_size_of_layers
    result += self.get_size_of_layer(repo, image_id)
  File "/root/docker_registry_frontend/cache.py", line 21, in decorator
    result = f(*args, **kwargs)
  File "/root/docker_registry_frontend/registry.py", line 338, in get_size_of_layer
    method='HEAD'
  File "/root/docker_registry_frontend/registry.py", line 64, in request
    return urllib.request.urlopen(request, timeout=3)
  File "/usr/local/lib/python3.6/urllib/request.py", line 223, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/local/lib/python3.6/urllib/request.py", line 526, in open
    response = self._open(req, data)
  File "/usr/local/lib/python3.6/urllib/request.py", line 544, in _open
    '_open', req)
  File "/usr/local/lib/python3.6/urllib/request.py", line 504, in _call_chain
    result = func(*args)
  File "/usr/local/lib/python3.6/urllib/request.py", line 1346, in http_open
    return self.do_open(http.client.HTTPConnection, req)
  File "/usr/local/lib/python3.6/urllib/request.py", line 1321, in do_open
    r = h.getresponse()
  File "/usr/local/lib/python3.6/http/client.py", line 1331, in getresponse
    response.begin()
  File "/usr/local/lib/python3.6/http/client.py", line 297, in begin
    version, status, reason = self._read_status()
  File "/usr/local/lib/python3.6/http/client.py", line 258, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "/usr/local/lib/python3.6/socket.py", line 586, in readinto
    return self._sock.recv_into(b)
socket.timeout: timed out
192.168.36.195 - - [08/Jun/2018 08:05:06] "GET /registry/docker-proxy-ua/repo/mssql2017/ HTTP/1.1" 500 -
```

**Comment by brennerm** [comment]
I'll have a look at it this weekend.

**Comment by brennerm** [comment]
Please check if the new http_timeout setting (available in the _allow-http-timeout-configuration_ branch) solves your problem.

**Comment by pavlovpetro** [comment]
I will check it soon.

**Comment by pavlovpetro** [comment]
Hi,
You know, when I reconfigured my infrastructure of Docker and replaced the registry ran on Windows to Linux the exception "timeout" ceased. I've not changed anything from the "allow-http-timeout-configuration" branch on the running registry-fronted yet. I'll watch for it some time and, if it work well, I will give feedback.

**Comment by pavlovpetro** [comment]
Unfortunately, it didn't help me. The Registry Fronted works well directly with the Local Registry only. But doesn't work well with the Proxy Cache.

**Comment by brennerm** [comment]
What exactly do you mean with proxy cache. Are you talking about something like this?
https://docs.docker.com/registry/recipes/mirror/

**Comment by pavlovpetro** [comment]
Yes.

**Comment by brennerm** [comment]
Haven't tested the frontend with a registry cache. Could be that it doesn't respond the same way a "normal" registry does. Will check in the next days.
