### ISSUE TITLE
500 Internal Server Error on delete tag

### ISSUE THREAD

**Issue by mikaellindemann** [brennerm/docker-registry-frontend#7]
When deleting a tag from docker-registry-frontend, I get a generic Internal Server Error.
Looking into the logs of the container, it seems that the registry itself reponds with a 301 Moved Permanently.

```
[2018-06-07 08:19:07,589] ERROR in app: Exception on /delete_tag [POST]
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.6/site-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "frontend.py", line 112, in delete_tag
    registry.delete_tag(repo, tag)
  File "/root/docker_registry_frontend/registry.py", line 290, in delete_tag
    method='DELETE'
  File "/root/docker_registry_frontend/registry.py", line 64, in request
    return urllib.request.urlopen(request, timeout=3)
  File "/usr/local/lib/python3.6/urllib/request.py", line 223, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/local/lib/python3.6/urllib/request.py", line 532, in open
    response = meth(req, response)
  File "/usr/local/lib/python3.6/urllib/request.py", line 642, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/local/lib/python3.6/urllib/request.py", line 564, in error
    result = self._call_chain(*args)
  File "/usr/local/lib/python3.6/urllib/request.py", line 504, in _call_chain
    result = func(*args)
  File "/usr/local/lib/python3.6/urllib/request.py", line 735, in http_error_302
    new = self.redirect_request(req, fp, code, msg, headers, newurl)
  File "/usr/local/lib/python3.6/urllib/request.py", line 673, in redirect_request
    raise HTTPError(req.full_url, code, msg, headers, fp)
urllib.error.HTTPError: HTTP Error 301: Moved Permanently
127.0.0.1 - - [07/Jun/2018 08:19:07] "POST /delete_tag?registry_name=registryname&repo=reponame&tag=tag-PR-39 HTTP/1.0" 500 -
```

Compose setup:

```
version: "3"
services:
  registry:
    image: registry:2
    ports:
      - 127.0.0.1:5000:5000
    environment:
      - REGISTRY_STORAGE_FILESYSTEM_ROOTDIRECTORY=/data
      - REGISTRY_STORAGE_DELETE_ENABLED=true
    volumes:
      - ./data:/data
    networks:
      - reg
  registry2-frontend:
    image: brennerm/docker-registry-frontend
    ports:
      - "5002:80"
    networks:
      - reg
networks:
  reg:

```

And the registry has been added with the following URL:
`http://registry:5000/`

Note that `registry:2` points to the latest 2.6.2 image from Docker Hub.

**Comment by brennerm** [comment]
Hey @mikaellindemann, seems like the endpoint for deleting tags changed in one of the last releases. I'll have a look and come back to you with further information.

**Comment by brennerm** [comment]
Solved the issue. It's a result of the trailing slash in the URL you set for the registry. 

With trailing slash:
```
$ curl -v -X DELETE 127.0.0.1:5000//v2/pi-hole/manifests/sha256:50479369dcff346cb3f8aef12557ec8ebaf787882eeb7c0f44c98d7bcac39a52                                                                
*   Trying 127.0.0.1...
* TCP_NODELAY set
* Connected to 127.0.0.1 (127.0.0.1) port 5000 (#0)
> DELETE //v2/pi-hole/manifests/sha256:50479369dcff346cb3f8aef12557ec8ebaf787882eeb7c0f44c98d7bcac39a52 HTTP/1.1                                                                                                  
> Host: 127.0.0.1:5000
> User-Agent: curl/7.60.0
> Accept: */*
>
< HTTP/1.1 301 Moved Permanently
< Docker-Distribution-Api-Version: registry/2.0
< Location: /v2/pi-hole/manifests/sha256:50479369dcff346cb3f8aef12557ec8ebaf787882eeb7c0f44c98d7bcac39a52
< Date: Thu, 07 Jun 2018 12:54:44 GMT
< Content-Length: 0
< Content-Type: text/plain; charset=utf-8
<
* Connection #0 to host 127.0.0.1 left intact
```

Without trailing slash
```
$ curl -v -X DELETE 127.0.0.1:5000/v2/pi-hole/manifests/sha256:50479369dcff346cb3f8aef12557ec8ebaf787882eeb7c0f44c98d7bcac39a52                                                                 
*   Trying 127.0.0.1...
* TCP_NODELAY set
* Connected to 127.0.0.1 (127.0.0.1) port 5000 (#0)
> DELETE /v2/pi-hole/manifests/sha256:50479369dcff346cb3f8aef12557ec8ebaf787882eeb7c0f44c98d7bcac39a52 HTTP/1.1                                                                                                   
> Host: 127.0.0.1:5000
> User-Agent: curl/7.60.0
> Accept: */*
>
< HTTP/1.1 202 Accepted
< Docker-Distribution-Api-Version: registry/2.0
< X-Content-Type-Options: nosniff
< Date: Thu, 07 Jun 2018 12:54:49 GMT
< Content-Length: 0
< Content-Type: text/plain; charset=utf-8
<
* Connection #0 to host 127.0.0.1 left intact
```

I'll fix the code in the next few days. For now you can just remove the trailing slash when adding the registry.

Thanks for finding and reporting this issue :+1:.

**Comment by mikaellindemann** [comment]
Thanks for the quick response - The workaround works nicely.
